########################################################################################
# Title:         Bizbox: Settings | Migrator | 'ansible.cfg' | Migration 01           #
# Author(s):     desimaniac                                                            #
# URL:           https://github.com/GrecoTechnology/Bizbox                                   #
# --                                                                                   #
########################################################################################
#                            GNU General Public License v3.0                           #
########################################################################################
---
- name: "Migrator | 'ansible.cfg' | Add default entries to 'ansible.cfg'"
  community.general.ini_file:
    path: "{{ playbook_dir }}/{{ file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    no_extra_spaces: false
    owner: "{{ bizbox_yml.stat.uid }}"
    group: "{{ bizbox_yml.stat.gid }}"
    mode: 0664
  register: ansible_cfg_update_status
  loop:
    - { section: 'defaults', option: 'inventory', value: './inventories/local' }
    - { section: 'defaults', option: 'roles_path', value: 'roles:resources/roles' }
    - { section: 'defaults', option: 'fact_path', value: './ansible_facts.d' }
    - { section: 'defaults', option: 'log_path', value: './bizbox.log' }
    - { section: 'defaults', option: 'callbacks_enabled', value: 'profile_tasks' }
    - { section: 'defaults', option: 'interpreter_python', value: '/usr/bin/python3' }
    - { section: 'defaults', option: 'remote_tmp', value: '/tmp/ansible' }
    - { section: 'defaults', option: 'force_color', value: 'True' }

- name: "Migrator | 'ansible.cfg' | Build 'files_updated_successfully' list"
  ansible.builtin.set_fact:
    files_updated_successfully: "{{ files_updated_successfully + [file] }}"
    exit_is_necessary: true
  when: item.changed
  loop: "{{ ansible_cfg_update_status.results }}"
